apiVersion: v1
kind: Secret
metadata:
  name: lms-secret
  namespace: lms

type: Opaque

stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
root@ip-10-0-0-79:/home/ubuntu/lms-k8s/k8s# cat configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-config
  namespace: lms

data:
  DB_HOST: "db-service"
  DB_PORT: "5432"
  DB_NAME: "lms"
  BACKEND_PORT: "5000"
